name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "22"
          distribution: "temurin"
          cache: "gradle"
      - name: Build JAR
        run: ./gradlew build
